apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: PostgreSQL
    url: postgres:5432
    database: ph_port_monitor
    user: port_monitoring_user
    secureJsonData:
      password: port_monitoring_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
